export enum TransactionType {
  INCOME = 'income',
  EXPENSE = 'expense',
}

// Changed from Enum to const array for easier extension
export const DEFAULT_CATEGORIES = [
  'Food',
  'Transport',
  'Shopping',
  'Utilities',
  'Salary',
  'Rent',
  'Entertainment',
  'Other'
] as const;

export interface Transaction {
  id: string;
  created_at: string;
  amount: number;
  type: TransactionType;
  category: string;
  slip_url: string | null;
  description?: string;
}

export interface Stats {
  balance: number;
  income: number;
  expense: number;
}

export interface BudgetSettings {
  enabled: boolean;
  limit: number;
  alertThreshold: number; // Percentage 0-100
}

export type Language = 'en' | 'th';

export const TRANSLATIONS = {
  en: {
    appTitle: 'Expense Tracker Pro',
    subTitle: 'Manage your personal finances and keep track of slips.',
    totalBalance: 'Total Balance',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    newTransaction: 'New Transaction',
    income: 'Income',
    expense: 'Expense',
    amount: 'Amount',
    category: 'Category',
    selectCategory: 'Select Category',
    addNewCategory: '+ Add New Category',
    typeCategory: 'Type category name...',
    note: 'Note (Optional)',
    notePlaceholder: 'What was this for?',
    slipImage: 'Slip Image (Optional)',
    clickToUpload: 'Click to upload slip',
    saveTransaction: 'Save Transaction',
    saving: 'Saving...',
    recentTransactions: 'Recent Transactions',
    items: 'items',
    date: 'Date',
    categoryNote: 'Category / Note',
    slip: 'Slip',
    noTransactions: 'No transactions found. Start by adding one!',
    loading: 'Loading data...',
    credit: 'Credit by Bus',
    connectionRequired: 'Connection Required',
    connectionDesc: 'To use the Expense Tracker, you need to connect it to a Supabase project. Please configure your environment variables.',
    chartTitle: 'Income vs Expense (Last 7 Active Days)',
    viewSlip: 'View Slip',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this transaction?',
    allCategories: 'All Categories',
    totalFor: 'Total for',
    filterByCategory: 'Filter by Category',
    viewDaily: 'Daily',
    viewMonthly: 'Monthly',
    viewPie: 'Summary',
    pieChartTitle: 'Expense Distribution by Category',
    monthlyChartTitle: 'Monthly Summary (Last 6 Months)',
    refresh: 'Refresh Data',
    exportCSV: 'Export CSV',
    importCSV: 'Import CSV',
    importSuccess: 'Successfully imported transactions!',
    importError: 'Error importing CSV. Please check format.',
    clearAll: 'Clear All Data',
    confirmClearAll: 'DANGER: Are you sure you want to delete ALL transactions? This cannot be undone.',
    downloadChart: 'Save Chart as Image',
    customCategories: 'My Categories',
    adminSettings: 'Admin Settings',
    adminLogin: 'Admin Login',
    enterPin: 'Enter PIN',
    login: 'Login',
    incorrectPin: 'Incorrect PIN',
    back: 'Back',
    manageCategories: 'Manage Categories',
    noCustomCategories: 'No custom categories added yet.',
    add: 'Add',
    deleteCategoryConfirm: 'Delete category',
    budgetConfig: 'Budget Configuration',
    setBudget: 'Monthly Budget Limit',
    threshold: 'Alert Threshold (%)',
    enableBudget: 'Enable Budgeting',
    dangerZone: 'Danger Zone',
    resetData: 'Reset All Data',
    resetDesc: 'Permanently remove all transactions from the database.',
    saveSettings: 'Save Settings',
    myProfile: 'My Profile',
    userNameInSlip: 'My Name in Slips',
    userNameDesc: 'Used for auto-detecting Income vs Expense',
    analyzing: 'AI Analyzing Slip...',
    autoFillSuccess: 'Auto-filled from slip!',
    scanSlip: 'Scan Slip (AI)',
    orManual: 'or enter manually',
    removeFile: 'Remove file',
    sender: 'Sender',
    receiver: 'Receiver',
  },
  th: {
    appTitle: 'บันทึกรายรับ-รายจ่าย',
    subTitle: 'จัดการการเงินส่วนบุคคลและเก็บรูปสลิปของคุณ',
    totalBalance: 'ยอดเงินคงเหลือ',
    totalIncome: 'รายรับรวม',
    totalExpense: 'รายจ่ายรวม',
    newTransaction: 'เพิ่มรายการใหม่',
    income: 'รายรับ',
    expense: 'รายจ่าย',
    amount: 'จำนวนเงิน',
    category: 'หมวดหมู่',
    selectCategory: 'เลือกหมวดหมู่',
    addNewCategory: '+ เพิ่มหมวดหมู่ใหม่',
    typeCategory: 'พิมพ์ชื่อหมวดหมู่...',
    note: 'บันทึกช่วยจำ (ไม่บังคับ)',
    notePlaceholder: 'รายละเอียดเพิ่มเติม...',
    slipImage: 'รูปสลิป (ไม่บังคับ)',
    clickToUpload: 'คลิกเพื่ออัปโหลดสลิป',
    saveTransaction: 'บันทึกรายการ',
    saving: 'กำลังบันทึก...',
    recentTransactions: 'รายการล่าสุด',
    items: 'รายการ',
    date: 'วันที่',
    categoryNote: 'หมวดหมู่ / บันทึก',
    slip: 'สลิป',
    noTransactions: 'ไม่พบรายการ เริ่มต้นด้วยการเพิ่มรายการแรก!',
    loading: 'กำลังโหลดข้อมูล...',
    credit: 'Credit by Bus',
    connectionRequired: 'จำเป็นต้องเชื่อมต่อระบบ',
    connectionDesc: 'เพื่อใช้งาน Expense Tracker คุณต้องเชื่อมต่อกับโปรเจกต์ Supabase โปรดตั้งค่า Environment Variables',
    chartTitle: 'รายรับ vs รายจ่าย (7 วันที่มีความเคลื่อนไหวล่าสุด)',
    viewSlip: 'ดูสลิป',
    delete: 'ลบรายการ',
    confirmDelete: 'คุณแน่ใจหรือไม่ที่จะลบรายการนี้?',
    allCategories: 'ทุกหมวดหมู่',
    totalFor: 'ยอดรวมสำหรับ',
    filterByCategory: 'กรองหมวดหมู่',
    viewDaily: 'รายวัน',
    viewMonthly: 'รายเดือน',
    viewPie: 'ภาพรวม',
    pieChartTitle: 'สัดส่วนรายจ่ายแยกตามหมวดหมู่',
    monthlyChartTitle: 'สรุปผลรายเดือน (6 เดือนล่าสุด)',
    refresh: 'รีเฟรชข้อมูล',
    exportCSV: 'ส่งออก CSV',
    importCSV: 'นำเข้า CSV',
    importSuccess: 'นำเข้าข้อมูลสำเร็จ!',
    importError: 'เกิดข้อผิดพลาดในการนำเข้า โปรดตรวจสอบรูปแบบไฟล์',
    clearAll: 'ลบข้อมูลทั้งหมด',
    confirmClearAll: 'คำเตือน: คุณแน่ใจหรือไม่ที่จะลบข้อมูล "ทั้งหมด"? การกระทำนี้ไม่สามารถย้อนกลับได้',
    downloadChart: 'บันทึกกราฟเป็นรูปภาพ',
    customCategories: 'หมวดหมู่ของฉัน',
    adminSettings: 'ตั้งค่าผู้ดูแลระบบ',
    adminLogin: 'เข้าสู่ระบบแอดมิน',
    enterPin: 'กรอกรหัส PIN',
    login: 'เข้าสู่ระบบ',
    incorrectPin: 'รหัสผ่านไม่ถูกต้อง',
    back: 'กลับ',
    manageCategories: 'จัดการหมวดหมู่',
    noCustomCategories: 'ยังไม่มีหมวดหมู่เพิ่มเติม',
    add: 'เพิ่ม',
    deleteCategoryConfirm: 'ลบหมวดหมู่',
    budgetConfig: 'ตั้งค่างบประมาณ',
    setBudget: 'งบประมาณรายเดือน',
    threshold: 'แจ้งเตือนเมื่อถึง (%)',
    enableBudget: 'เปิดใช้งานงบประมาณ',
    dangerZone: 'พื้นที่อันตราย',
    resetData: 'รีเซ็ตข้อมูลทั้งหมด',
    resetDesc: 'ลบข้อมูลรายการทั้งหมดออกจากฐานข้อมูลอย่างถาวร',
    saveSettings: 'บันทึกการตั้งค่า',
    myProfile: 'โปรไฟล์ของฉัน',
    userNameInSlip: 'ชื่อของฉันในสลิป',
    userNameDesc: 'ใช้สำหรับตรวจสอบว่าเป็น รายรับ หรือ รายจ่าย อัตโนมัติ',
    analyzing: 'AI กำลังวิเคราะห์สลิป...',
    autoFillSuccess: 'ดึงข้อมูลจากสลิปเรียบร้อย!',
    scanSlip: 'สแกนสลิป (AI)',
    orManual: 'หรือ กรอกข้อมูลเอง',
    removeFile: 'ลบไฟล์',
    sender: 'ผู้โอน',
    receiver: 'ผู้รับเงิน',
  }
};